### ISSUE TITLE
Wachen-Planung nur deutsche Version

### ISSUE THREAD

**Issue by Suchty112** [lostdesign/lss-layout-manager#10]
Hallöle,
Die Wachenplanung funktioniert leider nur zum teil in der englischen version. Nämlich nur bei den Feuerwachen siehe Screenshot. Ich hab mir euer Script angeschaut, und es liegt an den Gebäude ID's.
Hier in meinem/Eagle's GSM script sind die von Missionchief:
https://rawgit.com/Suchty112/GSM/master/script.dev.js

![fireshot pro screen capture 002 - missionchief_com - build your own control center in your city - www_missionchief_com_](https://cloud.githubusercontent.com/assets/1109899/12384250/0dab7fae-bdb0-11e5-8ba9-66ec6cf65d4a.png)

gruß Sanni ;)

**Comment by lostdesign** [comment]
Wird behoben :) Eventuell gibt es eine gesonderte Version für Missionchief oder es wird integriert.

**Comment by KLNorthdegree** [comment]
Mach das doch net zu du depp.

**Comment by lostdesign** [comment]
Safe mach ich das zu :smirk:

**Comment by Tsumiki-Chan** [comment]
Hab mich kurz mit lost abgesprochen. Wir werden für MissionChief eine eigene Version rausbringen. Hat ganz einfach den Grund, dass die Autoalarmierung, das Design e.t.c teilweise auf die englische Sprache umgeschrieben werden muss. Wird noch mehr bugs haben.

**Comment by Suchty112** [comment]
Alles klar wenn ihr hilfe braucht beim umschreiben, meldet euch ;) ich würds dann machen, damit ihr weiter arbeiten könnt ^^
