### ISSUE TITLE
Verbandseinsätze klappen nicht

### ISSUE THREAD

**Issue by ValoisMedoc** [lostdesign/lss-layout-manager#19]
HI! Ich nutze den NoMap Modus und bin auf Chrome Version 51.0.2704.103 m unterwegs.

Ich kann keine Verbandseinsätze von anderen aufrufen. Es lässt sich nicht anklicken.
Wenn ich freigeben, passt alles. 
Was mache ich falsch?
Valois

**Comment by lostdesign** [comment]
Wird diese Woche angeschaut.
